### ISSUE TITLE
Line clear feedback

### ISSUE THREAD

**Issue by trosh** [Brian-Catcow-B/tetrisn-t#45]
Biggest gripe: please add some kind of visual feedback when lines clear! It feels so weird to have no feedback that my heart skips a beat every time hah

**Comment by Brian-Catcow-B** [comment]
I will get this done sometime this week, probably.

**Comment by Brian-Catcow-B** [comment]
Fixed this, merged to dev, will merge to master soon and make a tag release with all the improvements. thanks
